schema_version: 1

context:
  name: chempy
  version: "0.10.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 999eef252386732e2b908192faa2d590eb0fa11576fcb52556e0fbe7d1f0ca12

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - matplotlib-base >=2.2.5
    - notebook >=5.7.8
    - numpy >=1.16.4
    - python >=${{ python_min }}
    - scipy >=1.2.3
    - sym >=0.3.4
    - sympy >=1.5.1
    - pytest
    - pyparsing
    - pulp
    - dot2tex
    - pyneqsys
    - pyodesys
    - quantities
    - tabulate

tests:
  - python:
      imports:
        - chempy
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: A package useful for chemistry written in Python.
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://github.com/bjodah/chempy

extra:
  recipe-maintainers:
    - ProfLeao
    - bjodah
    - jan-janssen
